[".config/fish/conf.d/fzf-git.fish"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf-git.sh/refs/heads/main/fzf-git.fish"
    refreshPeriod = "168h"

[".config/fish/conf.d/fzf-git.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf-git.sh/refs/heads/main/fzf-git.sh"
    refreshPeriod = "168h"
